export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_IMAGES = "FETCH_PRODUCT_IMAGES";
export const FETCH_PRODUCT_PATTERNS = "FETCH_PRODUCT_PATTERNS";
export const FETCH_PRODUCT_VIP_DASHBOARD = "FETCH_PRODUCT_VIP_DASHBOARD";
export const FETCH_SCANNED_PRODUCT = "FETCH_SCANNED_PRODUCT";
export const FETCH_ALLPRODUCT_IMAGES = "FETCH_ALLPRODUCT_IMAGES";
